#pragma once

#include <stdint.h>
#include <esp_err.h>

#ifdef CONFIG_DRIVER_LEDMATRIX_ENABLE

	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0 < 0
		#error "Ledmatrix driver enabled without any rows! Please configure row 0 or disable the ledmatrix driver."
	#endif

	#define LEDMATRIX_HEIGHT 1
	#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 2
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 3
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 4
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 5
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 6
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 7
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 8
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_8 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_8
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 9
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_9 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_8, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_9
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 10
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_10 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_8, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_9, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_10
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 11
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_11 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_8, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_9, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_10, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_11
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 12
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_12 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_8, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_9, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_10, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_11, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_12
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 13
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_13 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_8, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_9, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_10, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_11, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_12, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_13
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 14
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_14 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_8, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_9, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_10, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_11, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_12, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_13, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_14
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 15
	#if CONFIG_DRIVER_LEDMATRIX_PIN_ROW_15 >= 0
		#undef  DRIVER_LEDMATRIX_ROWS
		#define DRIVER_LEDMATRIX_ROWS CONFIG_DRIVER_LEDMATRIX_PIN_ROW_0, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_1, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_2, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_3, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_4, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_5, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_6, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_7, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_8, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_9, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_10, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_11, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_12, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_13, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_14, CONFIG_DRIVER_LEDMATRIX_PIN_ROW_15
		#undef LEDMATRIX_HEIGHT
		#define LEDMATRIX_HEIGHT 16
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0 < 0
		#error "Ledmatrix driver enabled without any columns! Please configure column 0 or disable the ledmatrix driver."
	#endif

	#define LEDMATRIX_WIDTH 1
	#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 2
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 3
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 4
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 5
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 6
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 7
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 8
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_8 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_8
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 9
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_9 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_8, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_9
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 10
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_10 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_8, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_9, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_10
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 11
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_11 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_8, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_9, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_10, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_11
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 12
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_12 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_8, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_9, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_10, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_11, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_12
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 13
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_13 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_8, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_9, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_10, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_11, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_12, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_13
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 14
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_14 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_8, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_9, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_10, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_11, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_12, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_13, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_14
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 15
	#if CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_15 >= 0
		#undef  DRIVER_LEDMATRIX_COLUMNS
		#define DRIVER_LEDMATRIX_COLUMNS CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_0, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_1, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_2, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_3, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_4, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_5, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_6, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_7, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_8, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_9, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_10, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_11, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_12, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_13, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_14, CONFIG_DRIVER_LEDMATRIX_PIN_COLUMN_15
		#undef LEDMATRIX_WIDTH
		#define LEDMATRIX_WIDTH 16
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	#endif
	
	extern esp_err_t driver_ledmatrix_set_buffer(const uint8_t *newBuffer);
	
	#define LEDMATRIX_BUFFER_SIZE LEDMATRIX_WIDTH*LEDMATRIX_HEIGHT
#endif

extern esp_err_t driver_ledmatrix_init(void);
